[[beans-factory-collaborators]]
= Dependency Injection(한글)

의존성 주입(DI)은 객체가 생성자 인수, 팩토리 메서드의 인수 또는 객체 인스턴스가 생성되거나 팩토리 메서드에서 반환된 후 객체 인스턴스에 설정된 속성을 통해서만 의존성(즉, 함께 작동하는 다른 객체)을 정의하는 프로세스입니다.
그런 다음 컨테이너는 빈을 생성할 때 이러한 의존성을 주입합니다.
이 프로세스는 기본적으로 클래스의 직접 구성 또는 서비스 로케이터 패턴을 사용하여 빈 자체가 의존성의 인스턴스화 또는 위치를 자체적으로 제어하는 역방향(따라서 이름, 제어의 역전)입니다.
DI 원칙을 사용하면 코드가 더 깔끔해지며, 객체에 의존성이 제공될 때 (역자설명 : 느슨한 결합)디커플링이 더 효과적입니다.
객체는 의존성을 조회하지 않으며 의존성의 위치나 클래스를 알지 못합니다.
결과적으로 클래스를 테스트하기가 더 쉬워지며, 특히 의존성이 인터페이스나 추상 베이스 클래스에 있는 경우 단위 테스트에서 스텁 또는 모의 구현을 사용할 수 있습니다.

DI는 크게 두 가지 변형이 있습니다: xref:core/beans/dependencies/factory-collaborators.adoc#beans-constructor-injection[생성자 기반 의존성 주입] 및 xref:core/beans/dependencies/factory-collaborators.adoc#beans-setter-injection[세터 기반 의존성 주입].


[[beans-constructor-injection]]
== 생성자 기반 종속성 주입(Constructor-based Dependency Injection)

생성자 기반 DI는 컨테이너가 여러 개의 인수를 사용하여 생성자를 호출하고 각 인수가 종속성을 나타내는 방식으로 수행됩니다.
특정 인수를 사용하여 `static` 팩토리 메서드를 호출하여 빈을 생성하는 것은 거의 동일하며, 이 설명에서는 생성자와 `static` 팩토리 메서드에 대한 인수를 비슷하게 취급합니다.
다음 예제는 생성자 주입으로만 종속성을 주입할 수 있는 클래스를 보여줍니다:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	public class SimpleMovieLister {

		// the SimpleMovieLister has a dependency on a MovieFinder
		private final MovieFinder movieFinder;

		// a constructor so that the Spring container can inject a MovieFinder
		public SimpleMovieLister(MovieFinder movieFinder) {
			this.movieFinder = movieFinder;
		}

		// business logic that actually uses the injected MovieFinder is omitted...
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	// a constructor so that the Spring container can inject a MovieFinder
	class SimpleMovieLister(private val movieFinder: MovieFinder) {
		// business logic that actually uses the injected MovieFinder is omitted...
	}
----
======

이 클래스에는 특별한 것이 없습니다. 컨테이너 특정 인터페이스, 베이스 클래스 또는 어노테이션에 대한 종속성이 없는 (역자설명 : Plain Old Java Object)POJO입니다.

[[beans-factory-ctor-arguments-resolution]]
=== 생성자 인수(Constructor Argument Resolution)

생성자 인수 매칭은 인자의 유형을 사용하여 발생합니다.
빈 정의의 생성자 인자에 잠재적인 모호성이 존재하지 않는 경우, 빈 정의에서 생성자 인자가 정의되는 순서는 빈이 인스턴스화될 때 해당 인자가 적절한 생성자에게 제공되는 순서입니다.
다음 클래스를 생각해 보세요:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary",chomp="-packages"]
----
	package x.y;

	public class ThingOne {

		public ThingOne(ThingTwo thingTwo, ThingThree thingThree) {
			// ...
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary",chomp="-packages"]
----
	package x.y

	class ThingOne(thingTwo: ThingTwo, thingThree: ThingThree)
----
======

`ThingTwo` 와 `ThingThree` 클래스가 상속으로 관련이 없다고 가정하면 잠재적인 모호성은 존재하지 않습니다.
따라서 다음 구성은 정상적으로 작동하며, 생성자 인자 인덱스나 유형을 `<constructor-arg/>` 요소에 명시적으로 지정할 필요가 없습니다.

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<beans>
		<bean id="beanOne" class="x.y.ThingOne">
			<constructor-arg ref="beanTwo"/>
			<constructor-arg ref="beanThree"/>
		</bean>

		<bean id="beanTwo" class="x.y.ThingTwo"/>

		<bean id="beanThree" class="x.y.ThingThree"/>
	</beans>
----

다른 빈을 참조하면 유형을 알 수 있으므로 앞의 예제에서와 같이 일치시킬 수 있습니다.
'<value>true</value>' 와 같은 단순한 타입이 사용되는 경우 Spring은 값의 타입을 확인할 수 없으므로 도움 없이는 타입별로 일치시킬 수 없습니다.
다음 클래스를 고려해 보겠습니다:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary",chomp="-packages"]
----
	package examples;

	public class ExampleBean {

		// Number of years to calculate the Ultimate Answer
		private final int years;

		// The Answer to Life, the Universe, and Everything
		private final String ultimateAnswer;

		public ExampleBean(int years, String ultimateAnswer) {
			this.years = years;
			this.ultimateAnswer = ultimateAnswer;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary",chomp="-packages"]
----
	package examples

	class ExampleBean(
		private val years: Int, // Number of years to calculate the Ultimate Answer
		private val ultimateAnswer: String // The Answer to Life, the Universe, and Everything
	)
----
======

.[[beans-factory-ctor-arguments-type]]생성자 인수 타입 일치
--
앞의 시나리오에서 컨테이너는 다음 예제와 같이 `type` 속성을 사용하여 생성자 인수의 유형을 명시적으로 지정하면 단순 유형과 유형 일치를 사용할 수 있습니다:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="exampleBean" class="examples.ExampleBean">
		<constructor-arg type="int" value="7500000"/>
		<constructor-arg type="java.lang.String" value="42"/>
	</bean>
----
--

.[[beans-factory-ctor-arguments-index]]생성자 인수 인덱스
--
다음 예시와 같이 `index` 속성을 사용하여 생성자 인수의 인덱스를 명시적으로 지정할 수 있습니다:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="exampleBean" class="examples.ExampleBean">
		<constructor-arg index="0" value="7500000"/>
		<constructor-arg index="1" value="42"/>
	</bean>
----

다음 예시와 같이 `index` 속성을 사용하여 생성자 인수의 인덱스를 명시적으로 지정할 수 있습니다:

NOTE: 인덱스는 0을 기준으로 합니다.
--

.[[beans-factory-ctor-arguments-name]]생성자 인수명
--
다음과 같이 생성자 매개변수 이름을 사용하여 값을 명확히 할 수도 있습니다.
예제에서 볼 수 있습니다:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="exampleBean" class="examples.ExampleBean">
		<constructor-arg name="years" value="7500000"/>
		<constructor-arg name="ultimateAnswer" value="42"/>
	</bean>
----

이 기능을 바로 사용하려면 Spring이 생성자에서 매개 변수 이름을 조회할 수 있도록 디버그 플래그를 활성화한 상태로 코드를 컴파일해야 합니다.
디버그 플래그를 사용하여 코드를 컴파일할 수 없거나 원하지 않는 경우 https://download.oracle.com/javase/8/docs/api/java/beans/ConstructorProperties.html[@ConstructorProperties] JDK 어노테이션을 사용하여 생성자 인수의 이름을 명시적으로 지정할 수 있습니다.
그러면 샘플 클래스는 다음과 같이 보일 것입니다:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary",chomp="-packages"]
----
	package examples;

	public class ExampleBean {

		// Fields omitted

		@ConstructorProperties({"years", "ultimateAnswer"})
		public ExampleBean(int years, String ultimateAnswer) {
			this.years = years;
			this.ultimateAnswer = ultimateAnswer;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary",chomp="-packages"]
----
	package examples

	class ExampleBean
	@ConstructorProperties("years", "ultimateAnswer")
	constructor(val years: Int, val ultimateAnswer: String)
----
======
--


[[beans-setter-injection]]
== 세터 기반 의존성 주입(Setter-based Dependency Injection)

세터 기반 DI(의존성 주입)는 인수가 없는 생성자 또는 인수가 없는 `static` 팩토리 메서드를 호출하여 빈을 인스턴스화한 후 컨테이너가 빈의 세터 메서드를 호출하여 수행됩니다.
다음 예제는 순수 세터 주입을 사용해야만 종속성 주입이 가능한 클래스를 보여줍니다.
이 클래스는 기존 Java입니다.
컨테이너 특정 인터페이스, 베이스 클래스 또는 어노테이션에 대한 종속성이 없는 POJO입니다.

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	public class SimpleMovieLister {

		// the SimpleMovieLister has a dependency on the MovieFinder
		private MovieFinder movieFinder;

		// a setter method so that the Spring container can inject a MovieFinder
		public void setMovieFinder(MovieFinder movieFinder) {
			this.movieFinder = movieFinder;
		}

		// business logic that actually uses the injected MovieFinder is omitted...
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
class SimpleMovieLister {

	// a late-initialized property so that the Spring container can inject a MovieFinder
	lateinit var movieFinder: MovieFinder

	// business logic that actually uses the injected MovieFinder is omitted...
}
----
======


`ApplicationContext` 는 관리하는 빈에 대해 생성자 기반 및 세터 기반 DI를 지원합니다.
또한 생성자 접근 방식을 통해 일부 종속성이 이미 주입된 후에도 세터 기반 DI를 지원합니다.
속성을 한 형식에서 다른 형식으로 변환하기 위해 `PropertyEditor` 인스턴스와 함께 사용하는 `BeanDefinition`의 형태로 종속성을 구성합니다.
그러나 대부분의 Spring 사용자는 이러한 클래스를 직접(즉, 프로그래밍 방식으로) 사용하는 것이 아니라 XML `bean` 정의, 주석이 달린 컴포넌트(즉, `@Component`, `@Controller` 등으로 주석이 달린 클래스) 또는 Java 기반 `@Configuration` 클래스의 `@Bean` 메서드를 사용하여 작업합니다.
그런 다음 이러한 소스는 내부적으로 `BeanDefinition` 의 인스턴스로 변환되어 전체 Spring IoC 컨테이너 인스턴스를 로드하는 데 사용됩니다.

[[beans-constructor-vs-setter-injection]]
.생성자-기반 또는 세터-기반 의존성 주입?(Constructor-based or setter-based DI?)
****
생성자 기반과 설정자 기반 DI를 혼합할 수 있으므로 필수 종속성에는 생성자를 사용하고 선택적 종속성에는 설정자 메서드 또는 구성 메서드를 사용하는 것이 좋은 경험 법칙입니다.
세터 메서드에 xref:core/beans/annotation-config/autowired.adoc[@Autowired] 어노테이션을 사용하면 속성을 필수 종속성으로 만들 수 있지만 인수의 프로그래밍 유효성 검사를 통해 생성자 주입을 사용하는 것이 바람직합니다.
Spring 팀은 일반적으로 생성자 주입을 옹호하는데, 이는 애플리케이션 구성 요소를 불변 객체로 구현할 수 있고 필수 종속성이 'null'이 되지 않도록 보장하기 때문입니다.
또한 생성자 주입된 컴포넌트는 항상 완전히 초기화된 상태로 클라이언트(호출) 코드에 반환됩니다.
참고로, 생성자 인수가 많다는 것은 코드 냄새가 좋지 않다는 의미이며, 클래스에 너무 많은 책임이 있을 수 있으므로 적절한 분리를 위해 리팩터링해야 한다는 뜻입니다.
세터 주입은 주로 클래스 내에서 합리적인 기본값을 할당할 수 있는 선택적 종속성에만 사용해야 합니다.
그렇지 않으면 코드가 종속성을 사용하는 모든 곳에서 null이 아닌 검사를 수행해야 합니다.
세터 주입의 한 가지 장점은 세터 메서드를 사용하면 해당 클래스의 객체를 나중에 재구성하거나 다시 주입할 수 있다는 것입니다.

따라서 xref:integration/jmx.adoc[JMX MBeans]를 통한 관리는 세터 인젝션의 강력한 사용 사례입니다.
특정 클래스에 가장 적합한 DI 스타일을 사용하세요.
때로는 소스가 없는 타사 클래스를 다룰 때는 사용자가 직접 선택해야 하는 경우도 있습니다.
예를 들어 타사 클래스에 설정자 메서드가 노출되지 않는 경우 생성자 주입이 사용 가능한 유일한 DI 형태일 수 있습니다.
****


[[beans-dependency-resolution]]
== 종속성 프로세스(Dependency Resolution Process)

컨테이너는 다음과 같이 빈 종속성 확인을 수행합니다:

* 모든 빈을 설명하는 구성 메타데이터로 `ApplicationContext` 가 생성되고 초기화됩니다.
구성 메타데이터는 XML, Java 코드 또는 어노테이션으로 지정할 수 있습니다.
* 각 빈의 종속성은 속성, 생성자 인수 또는 정적-팩토리 메서드(일반 생성자 대신 사용하는 경우)에 대한 인수의 형태로 표현됩니다.
이러한 종속성은 빈이 실제로 생성될 때 빈에 제공됩니다.
* 각 속성 또는 생성자 인수는 설정할 값의 실제 정의이거나 컨테이너의 다른 빈에 대한 참조입니다.
* 값인 각 속성 또는 생성자 인수는 지정된 형식에서 해당 속성 또는 생성자 인수의 실제 유형으로 변환됩니다.
기본적으로 Spring은 문자열 형식으로 제공된 값을 `int`, `long`, `String`, `boolean` 등과 같은 모든 기본 제공 유형으로 변환할 수 있습니다.

Spring 컨테이너는 컨테이너가 생성될 때 각 빈의 구성에 대한 유효성을 검사합니다.
그러나 빈 속성 자체는 빈이 실제로 생성될 때까지 설정되지 않습니다.
싱글톤 범위로 설정되고 사전 인스턴스화되도록 설정된 빈(기본값)은 컨테이너가 생성될 때 생성됩니다.
범위는 xref:core/beans/factory-scopes.adoc[Bean Scopes].에 정의되어 있습니다.
그렇지 않으면 요청이 있을 때만 빈이 생성됩니다.
빈을 생성하면 빈의 종속성과 그 종속성의 종속성 등이 생성되고 할당되므로 빈 그래프가 생성될 가능성이 있습니다.
이러한 종속성 간의 불일치는 늦게 나타날 수 있습니다. -- 즉, 영향을 받는 빈을 처음 생성할 때 나타날 수 있습니다.

.순환 종속(Circular dependencies)
****
생성자 주입을 주로 사용하는 경우 해결할 수 없는 순환 종속성 시나리오가 발생할 수 있습니다.

예를 들어 클래스 A는 생성자 주입을 통해 클래스 B의 인스턴스를 필요로 하고, 클래스 B는 생성자 주입을 통해 클래스 A의 인스턴스를 필요로 합니다.
클래스 A와 B에 대한 빈이 서로 주입되도록 구성하면 Spring IoC 컨테이너는 런타임에 이 순환 참조를 감지하고 `BeanCurrentlyInCreationException` 을 던집니다.

한 가지 가능한 해결책은 일부 클래스의 소스 코드를 생성자가 아닌 세터로 구성하도록 편집하는 것입니다.
또는 생성자 주입을 피하고 세터 주입만 사용하는 방법도 있습니다.
즉, 권장되지는 않지만 세터 주입으로 순환 종속성을 구성할 수 있습니다.

일반적인 경우(순환 종속성이 없는 경우)와 달리, 빈 A와 빈 B 사이의 순환 종속성은 빈 중 하나가 완전히 초기화되기 전에 다른 빈에 강제로 주입됩니다(고전적인 닭과 달걀 시나리오).
****

일반적으로 Spring이 올바른 작업을 수행한다고 믿을 수 있습니다.
Spring은 컨테이너 로드 시 존재하지 않는 빈에 대한 참조 및 순환 종속성과 같은 구성 문제를 감지합니다.
Spring은 빈이 실제로 생성될 때 가능한 한 늦게 속성을 설정하고 종속성을 해결합니다.
즉, 올바르게 로드된 Spring 컨테이너는 나중에 객체를 요청할 때 해당 객체 또는 해당 종속성 중 하나를 생성하는 데 문제가 있는 경우(예: 빈이 누락되거나 잘못된 속성으로 인해 예외를 던지는 경우) 예외를 생성할 수 있습니다.
일부 구성 문제에 대한 가시성이 지연될 수 있기 때문에 `ApplicationContext` 구현은 기본적으로 싱글톤 빈을 사전 인스턴스화합니다.
이러한 빈을 실제로 필요하기 전에 생성하는 데 약간의 시간과 메모리가 소요되지만, 나중에가 아니라 `ApplicationContext` 가 생성될 때 구성 문제를 발견할 수 있습니다.
이 기본 동작을 재정의하여 싱글톤 빈이 열심히 사전 인스턴스화되지 않고 느리게 초기화되도록 할 수 있습니다.

순환 종속성이 존재하지 않는 경우, 하나 이상의 협업 빈이 종속 빈에 주입될 때 각 협업 빈은 종속 빈에 주입되기 전에 완전히 구성됩니다.
즉, 빈 A에 빈 B에 대한 종속성이 있는 경우 Spring IoC 컨테이너는 빈 A에서 세터 메서드를 호출하기 전에 빈 B를 완전히 구성합니다.
즉, 빈이 인스턴스화되고(사전 인스턴스화된 싱글톤이 아닌 경우), 종속성이 설정되고, 관련 수명 주기 메서드(예: xref:core/beans/factory-nature.adoc#beans-factory-lifecycle-initializingbean[구성된 init 메서드] 또는 xref:core/beans/factory-nature.adoc#beans-factory-lifecycle-initializingbean[InitializingBean callback 메서드])가 호출되는 방식이죠.


[[beans-some-examples]]
== 의존성 주입 예제(Examples of Dependency Injection)

다음 예제는 세터 기반 DI에 XML 기반 구성 메타데이터를 사용합니다.
Spring XML 구성 파일의 작은 부분은 다음과 같이 몇 가지 빈 정의를 지정합니다:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="exampleBean" class="examples.ExampleBean">
		<!-- setter injection using the nested ref element -->
		<property name="beanOne">
			<ref bean="anotherExampleBean"/>
		</property>

		<!-- setter injection using the neater ref attribute -->
		<property name="beanTwo" ref="yetAnotherBean"/>
		<property name="integerProperty" value="1"/>
	</bean>

	<bean id="anotherExampleBean" class="examples.AnotherBean"/>
	<bean id="yetAnotherBean" class="examples.YetAnotherBean"/>
----

다음 예제는 해당 `ExampleBean` 클래스를 보여줍니다:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	public class ExampleBean {

		private AnotherBean beanOne;

		private YetAnotherBean beanTwo;

		private int i;

		public void setBeanOne(AnotherBean beanOne) {
			this.beanOne = beanOne;
		}

		public void setBeanTwo(YetAnotherBean beanTwo) {
			this.beanTwo = beanTwo;
		}

		public void setIntegerProperty(int i) {
			this.i = i;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
class ExampleBean {
	lateinit var beanOne: AnotherBean
	lateinit var beanTwo: YetAnotherBean
	var i: Int = 0
}
----
======

앞의 예제에서는 XML 파일에 지정된 속성과 일치하도록 세터가 선언되어 있습니다.
다음 예제에서는 생성자 기반 DI를 사용합니다:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="exampleBean" class="examples.ExampleBean">
		<!-- constructor injection using the nested ref element -->
		<constructor-arg>
			<ref bean="anotherExampleBean"/>
		</constructor-arg>

		<!-- constructor injection using the neater ref attribute -->
		<constructor-arg ref="yetAnotherBean"/>

		<constructor-arg type="int" value="1"/>
	</bean>

	<bean id="anotherExampleBean" class="examples.AnotherBean"/>
	<bean id="yetAnotherBean" class="examples.YetAnotherBean"/>
----

다음 예제는 해당 `ExampleBean` 클래스를 보여줍니다:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	public class ExampleBean {

		private AnotherBean beanOne;

		private YetAnotherBean beanTwo;

		private int i;

		public ExampleBean(
			AnotherBean anotherBean, YetAnotherBean yetAnotherBean, int i) {
			this.beanOne = anotherBean;
			this.beanTwo = yetAnotherBean;
			this.i = i;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
class ExampleBean(
		private val beanOne: AnotherBean,
		private val beanTwo: YetAnotherBean,
		private val i: Int)
----
======

빈 정의에 지정된 생성자 인수는 `ExampleBean` 의 생성자 인자로 사용됩니다.

이제 이 예제의 변형으로, 생성자를 사용하는 대신 Spring이 객체의 인스턴스를 반환하기 위해 `static` 팩토리 메서드를 호출하도록 지시하는 경우를 생각해 보겠습니다:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="exampleBean" class="examples.ExampleBean" factory-method="createInstance">
		<constructor-arg ref="anotherExampleBean"/>
		<constructor-arg ref="yetAnotherBean"/>
		<constructor-arg value="1"/>
	</bean>

	<bean id="anotherExampleBean" class="examples.AnotherBean"/>
	<bean id="yetAnotherBean" class="examples.YetAnotherBean"/>
----

다음 예제는 해당 `ExampleBean` 클래스를 보여줍니다:

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	public class ExampleBean {

		// a private constructor
		private ExampleBean(...) {
			...
		}

		// a static factory method; the arguments to this method can be
		// considered the dependencies of the bean that is returned,
		// regardless of how those arguments are actually used.
		public static ExampleBean createInstance (
			AnotherBean anotherBean, YetAnotherBean yetAnotherBean, int i) {

			ExampleBean eb = new ExampleBean (...);
			// some other operations...
			return eb;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
----
	class ExampleBean private constructor() {
		companion object {
			// a static factory method; the arguments to this method can be
			// considered the dependencies of the bean that is returned,
			// regardless of how those arguments are actually used.
			@JvmStatic
			fun createInstance(anotherBean: AnotherBean, yetAnotherBean: YetAnotherBean, i: Int): ExampleBean {
				val eb = ExampleBean (...)
				// some other operations...
				return eb
			}
		}
	}
----
======

`static` 팩토리 메서드에 대한 인수는 `<constructor-arg/>` 요소로 제공되며, 실제로 생성자가 사용된 것과 똑같습니다.
팩토리 메서드가 반환하는 클래스의 유형은 `정적` 팩토리 메서드가 포함된 클래스와 동일한 유형일 필요는 없습니다(이 예제에서는 동일하지만).
인스턴스(non-static) 팩토리 메서드는 본질적으로 동일한 방식으로 사용될 수 있으므로(`class` 속성 대신 `factory-bean` 속성을 사용하는 것 외에는) 여기서는 이러한 세부 사항에 대해서는 설명하지 않습니다.



